unitourguide/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('home', views.index, name='home'),
    path('signup', views.signup, name='signup'),
    path('signin', views.signin, name='signin'),
    path('logout', views.logoutpage, name='logout'),
    path('find_uni', views.find_uni, name='find_uni'),
    path('find_guide/<int:school_id>', views.find_guide, name='find_guide'),
    path('my_tour', views.my_tour, name='my_tour'),
    path('to_be_guide', views.to_be_guide, name='to_be_guide'),
    path('manage_guide', views.manage_guide, name='manage_guide'),
    path('my_profile', views.my_profile, name='my_profile'),
    path('my_info', views.my_info, name='my_info'),
    path('write_review/<int:tour_id>', views.write_review, name='write_review'),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

webapps/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('', include('unitourguide.urls')),
    path('admin/', admin.site.urls),
]

unitourguide/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

# Customer/Tourist: (name, email, user)
# class Customer(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     def __str__(self):
#         return str(self.id) + " " + (self.user.first_name + " " + self.user.last_name).lower()


# Guide: 
# (name, email, studentID, user, numberOfTours, rating, feedback, price(daily))
class Guide(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    studentID = models.CharField(max_length=20)
    num_of_tours = models.IntegerField(default=0)
    rating = models.FloatField(null=True, blank=True)
    # feedback by tour
    price = models.FloatField(null=True, blank=True)
    picture = models.ImageField(upload_to='pictures_gui/', default='pictures_gui/sample_guide.png')
    description = models.CharField(max_length=100, null=True)
    def __str__(self):
        return str(self.id) + " " + (self.user.username + " " + self.user.first_name + " " + self.user.last_name).lower()

# Manager: (name, email)
class Manager(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    def __str__(self):
        return str(self.id) + " " + (self.user.username + " " + self.user.first_name + " " + self.user.last_name).lower()


# School:
# (name, city, state, guides(many-to-many))
class School(models.Model):
    display = models.BooleanField(default=False)
    recommand = models.BooleanField(default=False)
    name = models.CharField(max_length=100)
    city = models.CharField(max_length=30)
    state = models.CharField(max_length=30)
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)
    guides = models.ManyToManyField(Guide)
    description = models.CharField(max_length=200, null=True, blank=True)
    picture = models.ImageField(upload_to='pictures_sch/', null=True, blank=True)

    def __str__(self):
        return str(self.id) + " " + self.name.lower()

# Tour:
# (date, school, guide(ForeignKey), customer(ManyToMany), condition(charField (‘pending’, ‘accepted’, ‘completed’, ‘cancelled’, ‘declined’))
class Tour(models.Model):
    date = models.DateField()
    school = models.ForeignKey(School, null=True, blank=True, on_delete=models.SET_NULL)
    guide = models.ForeignKey(Guide, null=True, blank=True, on_delete=models.SET_NULL)
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    PENDING = 'pending'
    ACCEPTED = 'accepted'
    COMPLETED = 'completed'
    CANCELLED = 'cancelled'
    DECLINED = 'declined'
    CONDITION_CHOICES = [(PENDING, 'pending'), (ACCEPTED, 'accepted'), (COMPLETED, 'completed'), (CANCELLED, 'cancelled'), (DECLINED, 'declined')]
    condition = models.CharField(max_length=11, choices=CONDITION_CHOICES)
    feedback = models.CharField(max_length=100, null=True, blank=True)
    rating = models.FloatField(blank=True,null=True)

    def __str__(self):
        return str(self.id)

# GuideApplication
class GuideApplication(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,related_name='application')
    email = models.EmailField()
    school = models.ForeignKey(School, on_delete=models.CASCADE)
    studentID = models.CharField(max_length=20)
    document = models.ImageField(upload_to='pictures_gui/', null=True, blank=True)
    PENDING = 'pending'
    APPROVED = 'approved'
  
    CONDITION_CHOICES = [(PENDING, 'pending'), (APPROVED, 'approved')]
    condition = models.CharField(max_length=11, choices=CONDITION_CHOICES)

unitourguide/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from .models import Tour

class SignupForm(forms.Form):
    username = forms.CharField(label='User name', max_length=20)
    firstname = forms.CharField(label='first name', max_length=20)
    lastname = forms.CharField(label='Last name', max_length=20)
    password = forms.CharField(label='Pass Word', max_length=20, widget=forms.PasswordInput)
    password1 = forms.CharField(widget=forms.PasswordInput, label="PasswordConfirmation")
    class Meta:
        fields = ("username", "firstname", "lastname", "password")
    def clean_username(self):
        username = self.cleaned_data.get('username')
        username_qs = User.objects.filter(username=username)
        if username_qs.exists():
            raise ValidationError("Username already exists, please choose another one")
        return username
    def clean_password1(self):
        password = self.cleaned_data.get('password')
        password1 = self.cleaned_data.get('password1')
        if password and password1 and password != password1:
            raise ValidationError("Password did n't match")
        return password1

class UploadImageFormID(forms.Form):
    image_ID = forms.ImageField()

class UploadImageFormUni(forms.Form):
    image_uni = forms.ImageField()

class UploadImageFormPhoto(forms.Form):
    image_photo = forms.ImageField()

class ReviewForm(forms.ModelForm):
    class Meta:        
        model = Tour        
        fields = ['rating','feedback']
    def clean(self):
        cleaned_data = self.cleaned_data
        feedback = cleaned_data['feedback']
        rating = cleaned_data['rating']
        if not feedback:
            raise ValidationError("Please enter your feedback.")
        if not rating:
            raise ValidationError("Please enter your rating.")
        if rating>5 or rating<0:
            raise ValidationError("Rating should between 0 and 5.")
        return cleaned_data

    

unitourguide/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http import HttpResponse
from django.contrib.auth.models import User, Group
from django.contrib.auth import authenticate, login, logout
from .forms import SignupForm, UploadImageFormID, UploadImageFormUni, ReviewForm, UploadImageFormPhoto
from .models import Guide, School, Manager, Tour, GuideApplication
from django.contrib.auth.decorators import login_required, permission_required
from django.utils.dateformat import DateFormat
from django.utils.timezone import datetime
from django.contrib.auth.decorators import user_passes_test

# Create your views here.

# The home page


def index(request):
    schools = School.objects.filter(recommand=True)
    return render(request, 'unitourguide/index.html', {"schools": schools})

# The sign in page


def signin(request):
    if request.user.is_authenticated:
        errormessage = "You have already logged in, please log out first to change the user"
        return render(request, 'unitourguide/signin.html', {"errormessage":  errormessage})
    errormessage = ""
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("/")
        else:
            errormessage = "User do not exist or password wrong"
            return render(request, 'unitourguide/signin.html', {"errormessage":  errormessage})
    return render(request, 'unitourguide/signin.html')

# The sigh up page


def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            account = form.cleaned_data['username']
            first = form.cleaned_data['firstname']
            last = form.cleaned_data['lastname']
            passcode = form.cleaned_data['password']
            user = User.objects.create_user(
                username=account, password=passcode)
            user.first_name = first
            user.last_name = last
            user.save()
            # user.groups.add(Group.objects.get(name='customer'))
            login(request, user)
            return redirect("/")
    else:
        form = SignupForm()
    return render(request, 'unitourguide/signup.html', {'form': form})


def find_uni(request):
    schools = School.objects.filter(display=True)
    errorMessage = ""
    if request.method == "GET":
        if ("search_by_name" in request.GET) and (len(request.GET["search_name"]) > 0):
            search_name = request.GET["search_name"]
            schools = School.objects.filter(name=search_name)
            if len(schools) == 0:
                errorMessage = "Sorry. We don't have any guides at " + search_name
                return render(request, 'unitourguide/find_uni.html', {"schools": schools, "errorMessage": errorMessage})
        if "filter_by_place" in request.GET:
            if "city_select" in request.GET:
                city = request.GET["city_select"]
                if city is not None:
                    schools = School.objects.filter(city=city)
                    return render(request, 'unitourguide/find_uni.html', {"schools": schools, })
            if "state_select" in request.GET:
                state = request.GET["state_select"]
                if state is not None:
                    schools = School.objects.filter(state=state)
                    return render(request, 'unitourguide/find_uni.html', {"schools": schools, })
    return render(request, 'unitourguide/find_uni.html', {"schools": schools, })


def find_guide(request, school_id):
    school = School.objects.get(id=school_id)
    guides = Guide.objects.filter(school=school).exclude(price=None)
    tours = Tour.objects.filter(school=school)
    message = "Here are all guides at %s." % school.name
    order = False
    date = None
    if request.method == 'GET':
        if "date" in request.GET and len(request.GET["date"]) > 0:
            date = request.GET["date"]
            tours2 = Tour.objects.filter(condition="accepted")
            if tours2 is not None:
                tours2 = tours2.filter(date=date)
                guides_to_exclude = [tour2.guide.id for tour2 in tours2]
                guides = guides.exclude(id__in=guides_to_exclude)
                if len(guides) > 0:
                    message = "Here are the available guides for date %s at %s." % (
                        date, school.name)
                else:
                    message = "Sorry. No available guides for date %s at %s." % (
                        date, school.name)
    if request.method == "POST" and "choose_guide" in request.POST and "guide_id" in request.POST:
        if not request.user.is_authenticated:
            return redirect(signin)
        guide_id = request.POST["guide_id"]
        guide = Guide.objects.get(id=guide_id)
        customer = request.user
        condition = "pending"
        if "hidden_date" in request.POST:
            date = request.POST["hidden_date"]
        if date == "None":
            date = datetime.today()
        tour = Tour(date=date, school=school, guide=guide,
                    customer=customer, condition=condition)
        tour.save()
        order = True
        message = "Thank you! Your order is on the way!"
    return render(request, 'unitourguide/find_guide.html', {"guides": guides, "school": school, "tours": tours, "message": message, "order": order, "hidden_date": date})


@login_required
def my_tour(request):
    current_user = request.user
    current_status = ['pending', 'accepted']
    past_status = ['completed', 'cancelled', 'declined']
    current_tours = Tour.objects.filter(
        customer=current_user).filter(condition__in=current_status)
    past_tours = Tour.objects.filter(
        customer=current_user).filter(condition__in=past_status)
    if request.method == 'POST' and "cancel" in request.POST:
        cancel_tour = Tour.objects.get(id=int(request.POST["cancel"]))
        cancel_tour.condition = "cancelled"
        cancel_tour.save()

    return render(request, 'unitourguide/my_tour.html', {"current_tours": current_tours, "past_tours": past_tours})


@login_required
def write_review(request, tour_id):
    tour = Tour.objects.get(id=tour_id)
    form = ReviewForm()
    if request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            feedback = form.cleaned_data['feedback']
            tour.feedback = feedback
            rating = form.cleaned_data['rating']
            tour.rating = rating
            tour.save()
            # update the guide's mean rating
            guide = tour.guide
            if not guide.rating:
                guide.rating = rating
            else:
                # get all tours of the guide
                tours = Tour.objects.filter(guide=guide)
                all_ratings = []
                for tour in tours:
                    if tour.rating:
                        all_ratings.append(tour.rating)
                guide.rating = round(sum(all_ratings)/len(all_ratings), 1)
            guide.save()
            return redirect("/")
    return render(request, 'unitourguide/write_review.html', {"form": form})


@login_required
def to_be_guide(request):
    schools = School.objects.all()
    message = ""
    display = True

    if Guide.objects.filter(user=request.user).exists():
        message = "You are already a guide. Don't apply again."
        display = False
        return render(request, 'unitourguide/to_be_guide.html', {"schools": schools, "message": message, "display": display})
    if GuideApplication.objects.filter(user=request.user).exists():
        message = "You already have a pending application. Don't apply again."
        display = False
        return render(request, 'unitourguide/to_be_guide.html', {"schools": schools, "message": message, "display": display})

    if request.method == 'POST':
        first_name = request.POST["first_name"]
        last_name = request.POST["last_name"]
        email = request.POST["email"]
        studentID = request.POST["studentid"]
        # state = request.POST["state_select"]
        # city = request.POST["city_select"]
        if not (first_name and last_name and email and studentID):
            message = "You must fill in all of the fields: First Name, Last Name, Email, and Student ID."
            return render(request, 'unitourguide/to_be_guide.html', {"schools": schools, "message": message, "display": display})

        if "school_select" not in request.POST:
            state_new = request.POST["state_name"]
            city_new = request.POST["city_input"]
            school_new_name = request.POST["other_uni"]
            school_description = request.POST["description"]

            if state_new and city_new and school_new_name and school_description:
                new_uni = School(name=school_new_name, state=state_new,
                                 city=city_new, description=school_description)
                uniform = UploadImageFormUni(request.POST, request.FILES)
                if uniform.is_valid():
                    new_uni.picture = uniform.cleaned_data["image_uni"]
                    new_uni.save()
                    school_id = new_uni.id
                else:
                    message = "You must upload a uni image."
                    return render(request, 'unitourguide/to_be_guide.html', {"schools": schools, "message": message, "display": display})
            else:
                message = "You must input state, city, and uni name."
                return render(request, 'unitourguide/to_be_guide.html', {"schools": schools, "message": message, "display": display})
        else:
            school_id = request.POST["school_select"]

        school = School.objects.get(id=school_id)

unitourguide/templates/unitourguide/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
  <title>{% block title %}University Tour Guide{% endblock %}</title>

  <!-- CSS  -->
  {% load static %}
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="{% static 'unitourguide/css/map.css' %}" rel="stylesheet">
  <link href="{% static 'unitourguide/css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="{% static 'unitourguide/css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="{% static 'unitourguide/css/home.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  {% block additional_css %}
  {% endblock %}
</head>

<body>
  <nav class="nav-extended">
      <div class="nav-wrapper teal">
        <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
        <img class="responsive-img" src="{% static 'unitourguide/img/onlylogo.png' %}" height="50" width="50"> Uni Tour Guide
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            {% if user.is_authenticated %}
            <li>Welcome, {{ user.username }}.</li>
            {% if perms.unitourguide.change_manager %}
            {% else %}
            {% if user.is_staff %}
            <li><a href="{% url 'my_profile' %}">My Profile</a></li>
            {% endif %}
            {% endif %}
            <li><a href="{% url 'logout' %}"><span class="white-text">Log out</span></a></li>
            {% else %}
            <li><a href="{% url 'signin' %}" class="teal">Log In</a></li>
            <li><a href="{% url 'signup' %}" class="teal">Sign Up</a></li>
            {% endif %}
        </ul>
        <ul class="side-nav" id="mobile-demo">
            {% if user.is_authenticated %}
            <li>Welcome, {{ user.username }}.</li>
            <li><a href="{% url 'logout' %}"><span class="white-text">Log out</span></a></li>
            {% else %}
            <li><a href="{% url 'signin' %}">Log In</a></li>
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
            {% endif %}
            <li><a target="_self" href="{% url 'home' %}">Home</a></li>
            <li><a target="_self" href="{% url 'find_uni' %}">Find a University</a></li>
            <li><a target="_self" href="{% url 'my_tour' %}">My Tour</a></li>
            {% if perms.unitourguide.change_manager %}
            <li><a target="_self" href="{% url 'manage_guide' %}">For Manager</a></li>
            {% else %}
            <li><a target="_self" href="{% url 'to_be_guide' %}">To be a Guide</a></li>
            {% endif %}
        </ul>
      </div>
      <div class="container">
          <div class="nav-content">
              <ul class="tabs tabs-transparent">
                  <li><a target="_self" href="{% url 'home' %}">Home</a></li>
                  <li><a target="_self" href="{% url 'find_uni' %}">Find a University</a></li>
                  <li><a target="_self" href="{% url 'my_tour' %}">My Tour</a></li>
                  {% if perms.unitourguide.change_manager %}
                  <li><a target="_self" href="{% url 'manage_guide' %}">For Manager</a></li>
                  {% else %}
                  <li><a target="_self" href="{% url 'to_be_guide' %}">To be a Guide</a></li>
                  {% endif %}
              </ul>
          </div>
      </div>
  </nav>

  <div class="container">
    {% block content %}
      <div class="row">
          {% for school in schools %}
          <div class="col l6 s12">
              <div class="card">
                  <div class="card-image waves-effect waves-block waves-light">
                    <img class="activator" src="{{ school.picture.url }}" alt="{{ school.name }}">
                  </div>
                  <div class="card-content">
                    <span class="card-title activator grey-text text-darken-4">{{ school.name }}<i class="material-icons right">more_vert</i></span>
                    <p><a href="{% url 'find_guide' school.id %}">Link to Guides</a></p>
                  </div>
                  <div class="card-reveal">
                    <span class="card-title grey-text text-darken-4">{{ school.name }}<i class="material-icons right">close</i></span>
                    <p>{{ school.description }}</p>
                  </div>
              </div>
          </div>
          {% endfor %}
      </div>
    {% endblock %}
  </div>

  <footer class="page-footer teal lighten-1">
    <div class="container">
      <div class="row">
          <div class="col s8">
              <h5 class="white-text">Uni Tour Guide</h5>
              <p class="grey-text text-lighten-4">This website is the project for the webapps course in CMU.
                The main purpose of this site is to build a platform for the tours who want to find a student guide
                and visit specific universities in the US.
              </p>
          </div>
          <img class="responsive-img" src="{% static 'unitourguide/img/logo.png' %}" height="200" width="300" >
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Made by UniTourGuide Project members: Jiaming Liu, Yue Yin, Yuhan He
      </div>
    </div>
  </footer>


  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="{% static 'unitourguide/js/materialize.js' %}"></script>
  <script src="{% static 'unitourguide/js/init.js' %}"></script>
  <script src="{% static 'unitourguide/js/map.js' %}"></script>
  {% block javascript %}
  {% endblock %}
  </body>
</html>

unitourguide/templates/unitourguide/logout.html
{% extends "unitourguide/index.html" %}
{% block title %} Log in {% endblock %}
{% block content %} 
<div class="container">
    <div class="row"><h4 class="red-text text-accent-2">Logged out</h4></div>
    <li>You are logged out successfully</li>
</div>
{% endblock %}

        

unitourguide/templates/unitourguide/manage_guide.html
{% extends "unitourguide/index.html" %}

<!-- CSS  -->
{% block additional_css %}
{% load static %}
<link href="{% static 'unitourguide/css/find_guide.css' %}" type="text/css" rel="stylesheet">
{% endblock %}

{% block title %} Manage Guide {% endblock %}

{% block content %}

<h4 class="red-text text-accent-2">Current Applications</h4>
<ul class="collapsible" data-collapsible="expandable">
    {% for app in applications %}
    <li>
        {% if forloop.counter == 1%}
        <div class="collapsible-header active">
            {% else %}
            <div class="collapsible-header">
                {% endif %}

                <div class="row">
                    <i class="large material-icons">assignment_ind</i>
                    <div class="col s3">Application Number: {{app.id}}</div>
                    <div class="col s3">Name: {{app.user.first_name}} {{app.user.last_name}}</div>
                    <div class="col s5">Uni: {{app.school.name}}</div>
                </div>
            </div>
            <ul class="collapsible-body">
                <div class="row">
                    <div class="col s6">
                        <li class="card_content_title">Student ID: </li>
                        <li> {{app.user.username}}</li>
                        <li class="card_content_title">Email: </li>
                        <li> {{app.user.email}}</li>
                        <li class="card_content_title">ID card: </li>
                        <li>
                            <img src="{{app.document.url}}" alt="idcard" height="200">
                        </li>

                    </div>
                    {% if not app.school.display %}
                    <div class="col s6">
                        <li class="card_content_title">Uni City & State: </li>
                        <li> {{app.school.city}}, {{app.school.state}}</li>
                        <li class="card_content_title">Uni Description: </li>
                        <li> {{app.school.description}}</li>
                        <li class="card_content_title">Uni Picture: </li>
                        <li>
                            <img src="{{app.school.picture.url}}" alt="uni_pic" height="200">
                        </li>
                    </div>
                    {% endif %}
                </div>
                <div class="row">


                    <div class="col s6 offset-s6">
                        <form method="POST">
                            {% csrf_token %}
                            {% if not app.school.display %}
                            <li>
                                <div class="row">
                                    <div class="input-field col s5">
                                        <input name="latitude" id="latitude" type="number" step="any" min="-90" max="90"
                                            class="validate">
                                        <label for="latitude">Latitude</label>
                                    </div>
                                    <div class="input-field col s5">
                                        <input name="longitude" id="longitude" type="number" step="any" min="-180"
                                            max="180" class="validate">
                                        <label for="longitude">Longitude</label>
                                    </div>
                                </div>
                            </li>
                            {% endif %}

                            <li>
                                <div class="row">
                                    <div class="col s6">
                                        <button class="btn waves-effect waves-light" type="submit" name="deny"
                                            value="{{app.id}}">Deny
                                            <i class="material-icons right">cancel</i>
                                        </button>
                                    </div>
                                    <div class="col s6">
                                        <button class="btn waves-effect waves-light" type="submit" name="approve"
                                            value="{{app.id}}">Approve
                                            <i class="material-icons right">done</i>
                                        </button>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <p class="alarm">{{ message }}</p>
                            </li>


                        </form>
                    </div>
                </div>



            </ul>
    </li>
    {% endfor %}

</ul>

<h4 class="red-text text-accent-2">Exsiting Guides</h4>

<ul class="collapsible" data-collapsible="expandable">
    {% for guide in guides %}
    <li>
        {% if forloop.counter == 1%}
        <div class="collapsible-header active">
            {% else %}
            <div class="collapsible-header">
                {% endif %}

                <div class="row">
                    <i class="large material-icons">assignment_ind</i>
                    <div class="col s3">Guide Number: {{guide.id}}</div>
                    <div class="col s3">Name: {{guide.user.first_name}} {{guide.user.last_name}}</div>

                    {% with guide.school_set.all|first as school %}
                    <div class="col s5">Uni: {{school.name}}</div>
                    {% endwith %}
                </div>
            </div>
            <ul class="collapsible-body">
                <li class="card_content_title">Student ID: </li>
                <li> {{guide.user.username}}</li>
                <li class="card_content_title">Email: </li>
                <li> {{guide.user.email}}</li>
                <li class="card_content_title">ID card: </li>
                <li>
                    <div class="col s6">
                        <img src="{{guide.user.application.document.url}}" alt="idcard" height="200">
                    </div>
                </li>
                <form method="POST">
                    {% csrf_token %}
                    <li>
                        <div class="row">
                            <div class="col s3 offset-s9">
                                <button class="btn waves-effect waves-light" type="submit" name="delete_guide"
                                    value="{{guide.id}}">Delete
                                    <i class="material-icons right">cancel</i>
                                </button>
                            </div>
                        </div>
                    </li>
                </form>

            </ul>
    </li>
    {% endfor %}

</ul>




{% endblock %}

unitourguide/templates/unitourguide/signin.html
{% extends "unitourguide/index.html" %}
{% block title %} Log in {% endblock %}
{% block content %} 
<div class="container">
    <div class="row"><h4 class="red-text text-accent-2">Log in</h4></div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %} <!-- csrf token for basic security -->
        <div class="inputContainer">
            <label for="username"><h5>User Name</h5></label>
            <input type="text" id="username" class="username" value="username" name="username" required>
            <label for="password"><h5>Password</h5></label>
            <input type="password" id="password" class="password" value="password" name="password" required>
            <p>{{ errormessage }}</p>
        </div>
        <div class="row">
            <button name="login" type="submit" class="waves-effect waves-light btn"><i class="fa fa-plus icon"></i>Log in</button>
            <div class="card-action">
                <a href="/signup">Sign up click here</a>
            </div>
        </div>
    </ul><!-- taskList -->
    </form>
</div>
{% endblock %}

        

unitourguide/templates/unitourguide/signup.html
{% extends "unitourguide/index.html" %}
{% block title %} Sign up {% endblock %}
{% block content %} 
<div class="container">
    <div class="row"><h4 class="red-text text-accent-2">Sign up</h4></div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %} <!-- csrf token for basic security -->
        <div class="inputContainer">
            {{ form }}
        </div>
        <div class="row">
            <button name="login" type="submit" class="waves-effect waves-light btn"><i class="fa fa-plus icon"></i>Sign Up</button>
        </div>
    </ul><!-- taskList -->
    </form>
</div>
{% endblock %}

        